name: Yaml integration tests

on:
  push:
    branches:
    - feature/master/yaml-test-runner
  pull_request:
    branches:
    - feature/master/yaml-test-runner

jobs:
  container-job:
    runs-on: ubuntu-latest
    
    container:
      image:  mcr.microsoft.com/dotnet/core/sdk:3.0

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT
        env:
          node.name: es1
          cluster.name: elasticsearch-gh-actions
          cluster.initial_master_nodes: es1
          discovery.seed_hosts: es1
          cluster.routing.allocation.disk.threshold_enabled: false
          bootstrap.memory_lock: true
          node.attr.testattr: test
          path.repo: tmp
          repositories.url.allowed_urls: http://snapshot.test
          ES_JAVA_OPTS: Xms1g -Xmx1g
        ports:
        - 9200:9200
        options: --health-cmd="curl -fsSL http://localhost:9200/_cat/health?h=status" --health-interval=5s --health-retries=12 --health-timeout=2s --ulimit nofile=65536:65536 --ulimit memlock=-1:-1 
        
    steps:
    - uses: actions/checkout@v1     
    - run: dotnet-run -f create -e http://elasticsearch:${{ job.services.elasticsearch.ports[9200] }} 
      working-directory: ./src/Tests/Tests.YamlRunner
